from enum import Enum

BRANCH_DIFF_REPORTER_DIR_NAME = "downstream-branchdiff-reporting"
PROJECT_NAME = "cdsw"
INSTALL_REQUIREMENTS_SCRIPT = "install-requirements.sh"
CDSW_RUNNER_PY = "cdsw_runner.py"


# TODO Add default value of all env vars to enum
class CdswEnvVar(Enum):
    MAIL_ACC_PASSWORD = "MAIL_ACC_PASSWORD"
    MAIL_ACC_USER = "MAIL_ACC_USER"
    MAIL_RECIPIENTS = "MAIL_RECIPIENTS"
    CLOUDERA_HADOOP_ROOT = "CLOUDERA_HADOOP_ROOT"
    HADOOP_DEV_DIR = "HADOOP_DEV_DIR"
    PYTHONPATH = "PYTHONPATH"
    TEST_EXECUTION_MODE = "TEST_EXEC_MODE"
    PYTHON_MODULE_MODE = "PYTHON_MODULE_MODE"


class BranchComparatorEnvVar(Enum):
    FEATURE_BRANCH = "BRANCH_COMP_FEATURE_BRANCH"
    MASTER_BRANCH = "BRANCH_COMP_MASTER_BRANCH"
    REPO_TYPE = "BRANCH_COMP_REPO_TYPE"


class JenkinsTestReporterEnvVar(Enum):
    BUILD_PROCESSING_LIMIT = "BUILD_PROCESSING_LIMIT"
    FORCE_SENDING_MAIL = "FORCE_SENDING_MAIL"
    RESET_JOB_BUILD_DATA = "RESET_JOB_BUILD_DATA"
