from enum import Enum

BRANCH_DIFF_REPORTER_DIR_NAME = "downstream-branchdiff-reporting"
JIRA_UMBRELLA_CHECKER_DIR_NAME = "jira-umbrella-checker"
UNIT_TEST_RESULT_AGGREGATOR_DIR_NAME = "unit-test-result-aggregator"
UNIT_TEST_RESULT_REPORTING_DIR_NAME = "unit-test-result-reporting"
PROJECT_NAME = "cdsw"
INSTALL_REQUIREMENTS_SCRIPT = "install-requirements.sh"
CDSW_RUNNER_PY = "cdsw_runner.py"


# TODO Add default value of all env vars to enum
class CdswEnvVar(Enum):
    MAIL_ACC_PASSWORD = "MAIL_ACC_PASSWORD"
    MAIL_ACC_USER = "MAIL_ACC_USER"
    MAIL_RECIPIENTS = "MAIL_RECIPIENTS"
    CLOUDERA_HADOOP_ROOT = "CLOUDERA_HADOOP_ROOT"
    HADOOP_DEV_DIR = "HADOOP_DEV_DIR"
    PYTHONPATH = "PYTHONPATH"
    TEST_EXECUTION_MODE = "TEST_EXEC_MODE"
    PYTHON_MODULE_MODE = "PYTHON_MODULE_MODE"
    ENABLE_GOOGLE_DRIVE_INTEGRATION = "ENABLE_GOOGLE_DRIVE_INTEGRATION"
    INSTALL_REQUIREMENTS = "INSTALL_REQUIREMENTS"
    RESTART_PROCESS_WHEN_REQUIREMENTS_INSTALLED = "RESTART_PROCESS_WHEN_REQUIREMENTS_INSTALLED"
