# set base image (host OS)
FROM python:3.8

WORKDIR /home/repos/snemeth/yarn-dev-tools/yarndevtools/cdsw
COPY requirements.txt .
RUN mkdir unit-test-result-reporting
RUN mkdir downstream-branchdiff-reporting
COPY unit-test-result-reporting unit-test-result-reporting/
COPY downstream-branchdiff-reporting downstream-branchdiff-reporting/
RUN pip install -r requirements-github.txt
RUN apt-get update && apt-get install -y --no-install-recommends \
        rsync

CMD [ "python", "./downstream-branchdiff-reporting/cdswsetup.py" ]