name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: pytest-results-3.8                           # artifact name
        name: Pytest Tests                                     # Name of the check run which will be created
        path: 'junit/test-results-3.8.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit                                   # Format of test results